### ISSUE TITLE
Plain text report is empty

### ISSUE THREAD

**Issue by andrefs** [ahemaid/RDF-Doctor#2]
When processing a file, the `.error` and `.output` files are empty.

Example file `test.ttl` (extracted from DBpedia v1 -- line 3 is missing a `>` to close the object):

```
<http://dbpedia.org/resource/%C3%96sterreichische_Nationalbibliothek> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/class/yago/Building> .
<http://dbpedia.org/resource/%C3%96sterreichische_Nationalbibliothek> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/class/yago/Library> .
<http://dbpedia.org/resource/%C3%96sterreichische_Postsparkasse> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/class/yago/DepositoryFinancialInstitutio .
<http://dbpedia.org/resource/%C3%96sterreichring> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/class/yago/Circuit> .
<http://dbpedia.org/resource/%C3%96stersunds_FK> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/class/yago/Club> .
```

Running RDF-Doctor with `java -jar RDFDoctor.jar -i test.ttl` it prints only the following (no Correction Report):
```
test.error
test.output
Processing is going on 

Total elapsed time: 278 ms

Number of processed lines: 6
```

The files `test.output` and `test.error` are created but empty.

If running with the `-j` option (everything else being the same), `test.output` is still empty, but `test.error` contains:
```
[{"errorMessage":"line 3:115 token recognition error at: '<http://dbpedia.org/class/yago/DepositoryFinancialInstitutio .\\n'\n<http://dbpedia.org/resource/%C3%96sterreichische_Postsparkasse> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/class/yago/DepositoryFinancialInstitutio .\n\n                                                                                                                   ^                                                              ","errorNumber":1},{"errorMessage":"line 4:50 Missing '.' at the end of a triple\n<http://dbpedia.org/resource/%C3%96sterreichring> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/class/yago/Circuit> .\n\n                                                  ^                                                                                           ","errorNumber":2},{"errorMessage":"line 4:140 Object of a triple is missing\n<http://dbpedia.org/resource/%C3%96sterreichring> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/class/yago/Circuit> .\n\n                                                                                                                                            ^ ","errorNumber":3}]
```

**Comment by andrefs** [comment]
Also, when running with the `-c` option:
```
test.error
test.output
Processing is going on -1
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at errorCorrection.Correction.addDot(Correction.java:147)
	at errorCorrection.Correction.process(Correction.java:36)
	at main.Main.parse(Main.java:245)
	at main.Main.main(Main.java:139)
	... 5 more
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

And it seems to continue to print more `!` indefinitely.
